version: '2'
services:
  rainloop:
    container_name: "rainloop"
    image: interlegis/alpine-rainloop:1.12.1
#    build: .
    volumes:
      - ./data:/var/www/rainloop/data
    ports:
      - "80:80"
